import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";
import { twMerge } from "tailwind-merge";

const geist = Geist({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body className={twMerge(geist.className, 'h-full')}>
        {children}
      </body>
    </html>
  );
}
